/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteRouteImport } from './routes/library/route'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as LibrarySplatRouteImport } from './routes/library/$'

const ComponentsSlugLazyRouteImport = createFileRoute('/components/$slug')()

const LibraryRouteRoute = LibraryRouteRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRouteRoute,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsSlugLazyRoute = ComponentsSlugLazyRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/$slug.lazy').then((d) => d.Route),
)
const LibrarySplatRoute = LibrarySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LibraryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/library': typeof LibraryRouteRouteWithChildren
  '/library/$': typeof LibrarySplatRoute
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library/$': typeof LibrarySplatRoute
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/components': typeof ComponentsIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/library': typeof LibraryRouteRouteWithChildren
  '/library/$': typeof LibrarySplatRoute
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/library'
    | '/library/$'
    | '/components/$slug'
    | '/components/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library/$' | '/components/$slug' | '/components' | '/library'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/library'
    | '/library/$'
    | '/components/$slug'
    | '/components/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
  LibraryRouteRoute: typeof LibraryRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/library/$': {
      id: '/library/$'
      path: '/$'
      fullPath: '/library/$'
      preLoaderRoute: typeof LibrarySplatRouteImport
      parentRoute: typeof LibraryRouteRoute
    }
  }
}

interface ComponentsRouteRouteChildren {
  ComponentsSlugLazyRoute: typeof ComponentsSlugLazyRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsSlugLazyRoute: ComponentsSlugLazyRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

interface LibraryRouteRouteChildren {
  LibrarySplatRoute: typeof LibrarySplatRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteRouteChildren: LibraryRouteRouteChildren = {
  LibrarySplatRoute: LibrarySplatRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteRouteWithChildren = LibraryRouteRoute._addFileChildren(
  LibraryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
  LibraryRouteRoute: LibraryRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
